import { useState, useCallback, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { 
  MapPin, 
  Phone, 
  Star, 
  Clock, 
  Navigation, 
  Copy, 
  Check, 
  Wrench,
  ExternalLink,
  Loader2,
  Search,
  AlertCircle
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface DiagnosticInfo {
  errorCode: string;
  manufacturer: string;
  model?: string;
  description: string;
  troubleshootingSteps?: string[];
  requiredParts?: string[];
  quickFix?: string;
}

interface ServiceTech {
  id: string;
  name: string;
  address: string;
  phone?: string;
  rating?: number;
  reviewCount?: number;
  openNow?: boolean;
  distance?: string;
  placeId: string;
  website?: string;
  types?: string[];
}

interface ServiceTechLocatorProps {
  diagnosticInfo?: DiagnosticInfo;
  compact?: boolean;
  onTechSelected?: (tech: ServiceTech, handoffSummary: string) => void;
}

export function ServiceTechLocator({ diagnosticInfo, compact = false, onTechSelected }: ServiceTechLocatorProps) {
  const [location, setLocation] = useState("");
  const [searching, setSearching] = useState(false);
  const [results, setResults] = useState<ServiceTech[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [selectedTech, setSelectedTech] = useState<ServiceTech | null>(null);
  const [copied, setCopied] = useState(false);
  const [userCoords, setUserCoords] = useState<{lat: number, lng: number} | null>(null);
  const { toast } = useToast();

  const generateHandoffSummary = useCallback(() => {
    if (!diagnosticInfo) return "";
    
    let summary = `=== SERVICE TECH HANDOFF ===\n\n`;
    summary += `EQUIPMENT: ${diagnosticInfo.manufacturer}${diagnosticInfo.model ? ` ${diagnosticInfo.model}` : ''}\n`;
    summary += `ERROR CODE: ${diagnosticInfo.errorCode}\n`;
    summary += `ISSUE: ${diagnosticInfo.description}\n\n`;
    
    if (diagnosticInfo.quickFix) {
      summary += `QUICK FIX ATTEMPTED: ${diagnosticInfo.quickFix}\n\n`;
    }
    
    if (diagnosticInfo.troubleshootingSteps?.length) {
      summary += `TROUBLESHOOTING COMPLETED:\n`;
      diagnosticInfo.troubleshootingSteps.forEach((step, i) => {
        summary += `${i + 1}. ${step}\n`;
      });
      summary += `\n`;
    }
    
    if (diagnosticInfo.requiredParts?.length) {
      summary += `LIKELY PARTS NEEDED:\n`;
      diagnosticInfo.requiredParts.forEach(part => {
        summary += `• ${part}\n`;
      });
      summary += `\n`;
    }
    
    summary += `--- Generated by Service Guy AI ---\n`;
    summary += `Save time: Tech arrives prepared with diagnosis and parts list.`;
    
    return summary;
  }, [diagnosticInfo]);

  const detectLocation = useCallback(() => {
    if (!navigator.geolocation) {
      setError("Geolocation is not supported by your browser");
      return;
    }

    setSearching(true);
    navigator.geolocation.getCurrentPosition(
      (position) => {
        setUserCoords({
          lat: position.coords.latitude,
          lng: position.coords.longitude
        });
        setLocation("Current Location");
        searchNearbyTechs(position.coords.latitude, position.coords.longitude);
      },
      (err) => {
        setSearching(false);
        setError("Unable to get your location. Please enter a ZIP code or address.");
      }
    );
  }, []);

  const searchNearbyTechs = async (lat: number, lng: number) => {
    setSearching(true);
    setError(null);

    try {
      const response = await fetch(`/api/service-techs/nearby?lat=${lat}&lng=${lng}&type=appliance_repair`);
      
      if (!response.ok) {
        throw new Error("Failed to search for service technicians");
      }
      
      const data = await response.json();
      setResults(data.results || []);
      
      if (data.results?.length === 0) {
        setError("No appliance repair services found nearby. Try expanding your search area.");
      }
    } catch (err) {
      setError("Unable to search for technicians. Please try again.");
      setResults([]);
    } finally {
      setSearching(false);
    }
  };

  const searchByAddress = async () => {
    if (!location.trim()) {
      setError("Please enter a location or ZIP code");
      return;
    }

    setSearching(true);
    setError(null);

    try {
      const response = await fetch(`/api/service-techs/search?address=${encodeURIComponent(location)}&type=appliance_repair`);
      
      if (!response.ok) {
        throw new Error("Failed to search for service technicians");
      }
      
      const data = await response.json();
      setResults(data.results || []);
      setUserCoords(data.coordinates || null);
      
      if (data.results?.length === 0) {
        setError("No appliance repair services found in this area. Try a different location.");
      }
    } catch (err) {
      setError("Unable to search for technicians. Please try again.");
      setResults([]);
    } finally {
      setSearching(false);
    }
  };

  const copyHandoff = async () => {
    const summary = generateHandoffSummary();
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      toast({
        title: "Copied to clipboard",
        description: "Diagnostic summary ready to share with tech"
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast({
        title: "Copy failed",
        description: "Please manually select and copy the text",
        variant: "destructive"
      });
    }
  };

  const callTech = (phone: string) => {
    window.open(`tel:${phone}`, '_self');
  };

  const getDirections = (address: string) => {
    const encodedAddress = encodeURIComponent(address);
    window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodedAddress}`, '_blank');
  };

  return (
    <div className="space-y-4" data-testid="service-tech-locator">
      <div className="flex flex-col sm:flex-row gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="Enter ZIP code or address..."
            value={location}
            onChange={(e) => setLocation(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && searchByAddress()}
            className="pl-10"
            data-testid="input-tech-location"
          />
        </div>
        <div className="flex gap-2">
          <Button
            onClick={searchByAddress}
            disabled={searching}
            data-testid="button-search-techs"
          >
            {searching ? <Loader2 className="w-4 h-4 animate-spin" /> : "Search"}
          </Button>
          <Button
            variant="outline"
            onClick={detectLocation}
            disabled={searching}
            data-testid="button-use-location"
          >
            <MapPin className="w-4 h-4 mr-1" />
            Use My Location
          </Button>
        </div>
      </div>

      {error && (
        <div className="flex items-center gap-2 text-sm text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/30 p-3 rounded-md">
          <AlertCircle className="w-4 h-4 flex-shrink-0" />
          {error}
        </div>
      )}

      {diagnosticInfo && (
        <Card className="border-blue-200 dark:border-blue-900 bg-blue-50/50 dark:bg-blue-950/20">
          <CardHeader className="py-3">
            <CardTitle className="text-sm flex items-center justify-between gap-2 flex-wrap">
              <span className="flex items-center gap-2">
                <Wrench className="w-4 h-4 text-blue-500" />
                Issue Summary for Service Tech
              </span>
              <Button
                size="sm"
                variant="outline"
                onClick={copyHandoff}
                className="h-7"
                data-testid="button-copy-handoff"
              >
                {copied ? <Check className="w-3 h-3 mr-1" /> : <Copy className="w-3 h-3 mr-1" />}
                {copied ? "Copied!" : "Copy Summary"}
              </Button>
            </CardTitle>
          </CardHeader>
          <CardContent className="py-2">
            <div className="text-sm space-y-1">
              <p><strong>Equipment:</strong> {diagnosticInfo.manufacturer}{diagnosticInfo.model ? ` ${diagnosticInfo.model}` : ''}</p>
              <p><strong>Error:</strong> {diagnosticInfo.errorCode} - {diagnosticInfo.description}</p>
              {diagnosticInfo.requiredParts?.length ? (
                <p><strong>Parts Likely Needed:</strong> {diagnosticInfo.requiredParts.join(', ')}</p>
              ) : null}
            </div>
          </CardContent>
        </Card>
      )}

      {searching && (
        <div className="flex items-center justify-center py-8">
          <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
        </div>
      )}

      {results.length > 0 && (
        <div className="space-y-3">
          <p className="text-sm text-muted-foreground">
            Found {results.length} appliance repair service{results.length !== 1 ? 's' : ''} nearby
          </p>
          
          <div className={compact ? "space-y-2" : "grid gap-3 md:grid-cols-2"}>
            {results.map((tech) => (
              <Card 
                key={tech.id} 
                className="hover-elevate cursor-pointer"
                onClick={() => setSelectedTech(tech)}
                data-testid={`card-tech-${tech.id}`}
              >
                <CardContent className="p-4">
                  <div className="flex justify-between items-start gap-2">
                    <div className="flex-1 min-w-0">
                      <h4 className="font-semibold text-sm truncate">{tech.name}</h4>
                      <p className="text-xs text-muted-foreground truncate">{tech.address}</p>
                    </div>
                    {tech.rating && (
                      <Badge variant="secondary" className="flex items-center gap-1 flex-shrink-0">
                        <Star className="w-3 h-3 text-yellow-500 fill-yellow-500" />
                        {tech.rating.toFixed(1)}
                        {tech.reviewCount && <span className="text-muted-foreground">({tech.reviewCount})</span>}
                      </Badge>
                    )}
                  </div>
                  
                  <div className="flex flex-wrap items-center gap-2 mt-3">
                    {tech.openNow !== undefined && (
                      <Badge variant={tech.openNow ? "default" : "outline"} className="text-xs">
                        <Clock className="w-3 h-3 mr-1" />
                        {tech.openNow ? "Open Now" : "Closed"}
                      </Badge>
                    )}
                    {tech.distance && (
                      <Badge variant="outline" className="text-xs">
                        <Navigation className="w-3 h-3 mr-1" />
                        {tech.distance}
                      </Badge>
                    )}
                  </div>

                  <div className="flex flex-wrap gap-2 mt-3">
                    {tech.phone && (
                      <Button 
                        size="sm" 
                        variant="default"
                        onClick={(e) => { e.stopPropagation(); callTech(tech.phone!); }}
                        data-testid={`button-call-${tech.id}`}
                      >
                        <Phone className="w-3 h-3 mr-1" />
                        Call
                      </Button>
                    )}
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={(e) => { e.stopPropagation(); getDirections(tech.address); }}
                      data-testid={`button-directions-${tech.id}`}
                    >
                      <Navigation className="w-3 h-3 mr-1" />
                      Directions
                    </Button>
                    {tech.website && (
                      <a 
                        href={tech.website} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        onClick={(e) => e.stopPropagation()}
                      >
                        <Button size="sm" variant="outline" data-testid={`button-website-${tech.id}`}>
                          <ExternalLink className="w-3 h-3 mr-1" />
                          Website
                        </Button>
                      </a>
                    )}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {!searching && results.length === 0 && !error && (
        <div className="text-center py-8 text-muted-foreground">
          <MapPin className="w-12 h-12 mx-auto mb-3 opacity-50" />
          <p className="text-sm">Enter your location to find nearby appliance repair technicians</p>
          <p className="text-xs mt-1">They'll arrive prepared with your diagnosis and parts list</p>
        </div>
      )}
    </div>
  );
}

export function ServiceTechButton({ diagnosticInfo, className }: { diagnosticInfo: DiagnosticInfo; className?: string }) {
  const [open, setOpen] = useState(false);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button 
          variant="outline" 
          size="sm" 
          className={className}
          data-testid="button-find-service-tech"
        >
          <Wrench className="w-4 h-4 mr-1" />
          Find Service Tech
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wrench className="w-5 h-5 text-primary" />
            Find a Service Technician Nearby
          </DialogTitle>
        </DialogHeader>
        <ServiceTechLocator diagnosticInfo={diagnosticInfo} />
      </DialogContent>
    </Dialog>
  );
}
